# -*- coding: utf-8 -*-
"""Pset1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nzMc1vn7B5vcRgPT-wOSWnGDRDOZnnhf
"""

numero = list(input())
lista = []
validacao = []

## Transforma os valores da lista do cartão em valores INTEIROS para que seja possível valida-lo.
for val in numero:
  lista.append(int(val))

## Verifica se o cartão possui a quantidade de dígitos necessários relacionado as bandeiras.
if len(lista) > 16:
  print('Cartão Inválido')
else:
## Começa o processo de validação por meio do algaritimo de Luhn.
  for x in list(reversed(lista))[1::2]:
   numero_validacao= 2 * x
   validacao.append(numero_validacao)

final_lista = []
for x in list(validacao):
  if x > 9:
    subtracao = x-9 ## Qualquer número de Dois dígitos subtraido de 9 é a soma de dois dígitos
    final_lista.append(subtracao)
  else:
    final_lista.append(x)
for x in list(reversed(lista))[::2]:
    final_lista.append(x)
## Demonstra a bandeira do cartão se ele passar no proceço de validação.
if sum(final_lista)%10==0:
  if lista[0] == 3 and (lista[1]== 4 or 7):
    print("AMEX") 
  elif lista[0] == 5 and (lista[1]== 1 or 2 or 3 or 4 or 5):
    print("MASTERCARD")
  elif lista[0] == 4:
    print("VISA")
  else:
    print("inválido")
else:
  print("inválido")
